---
title: "map-demoines"
output: html_document
date: "2026-03-05"
---

```{r setup, include=FALSE}
library(sf)
library(ggplot2)
library(maps)
library(dplyr)
```

```{r}
sites <- data.frame(
  site = "Des Moines Marina",
  lon  = -122.329028,
  lat  = 47.397556
)

cities <- data.frame(
  city = c("Seattle", "Tacoma"),
  lon = c(-122.3321, -122.4443),
  lat = c(47.6062, 47.2529)
)

sites_sf <- st_as_sf(sites, coords = c("lon", "lat"), crs = 4326)

wa <- map_data("state") %>%
  filter(region == "washington")
```

```{r}
#world distribution, csv downloaded from aquamaps
#https://www.aquamaps.org/receive.php?type_of_map=regular&map=cached#
aqua <- read.csv(file = "../data/botryllus_aquamaps.csv")

world <- map_data("world")

```
PNW
```{r}
png(filename = "../output/de_moines_map.png", width = 600, height = 950)
ggplot() +
  geom_polygon(
    data = wa,
    aes(x = long, y = lat, group = group),
    fill = "grey90",
    color = "lightblue",
    linewidth = 0.3
  ) +
  geom_sf(data = sites_sf, size = 5, color = "red") +
  geom_text(
    data = sites,
    aes(x = lon, y = lat, label = site),
    nudge_y = 0.05,
    size = 8
  ) +
  geom_text(
  data = cities,
  aes(x = lon, y = lat, label = city),
  size = 8,
  fontface = "bold"
)+
  annotate(
    "text",
    x = -122.45,
    y = 47.75,
    label = "Puget Sound",
    size = 10,
    fontface = "italic",
    color = "navy"
  ) +
  coord_sf(
    xlim = c(-123.4, -122.0),
    ylim = c(47.0, 48.5),
    expand = FALSE
  ) +
  scale_x_continuous(
  breaks = seq(-123.5, -122.0, by = 0.5)) +
  theme_classic() +
  labs(
    x = "Longitude",
    y = "Latitude"
  )+
  theme(
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 15)
  ) 
dev.off()
```

World
```{r}
png(
  filename = "../output/global.png",
  width = 1300,
  height = 950,
  res = 200
)
ggplot() +
  geom_polygon(
    data = world,
    aes(x = long, y = lat, group = group),
    fill = "grey80",
    color = "grey50",
    linewidth = 0.2
  ) +
  geom_point(
    data = aqua,
    aes(x = `Center.Long`, y = `Center.Lat`, color = `Overall.Probability`),
    size = 0.6
  ) +
  scale_color_viridis_c(name = "Occurance Probability",
                        breaks = c(0.0,0.25,0.5,0.75)) +
  coord_fixed(1.3) +
  theme_classic() +
  labs(
    subtitle = "Data Provided by AquaMaps (2019, October)",
    x = "Longitude",
    y = "Latitude"
  )+
  theme(
  legend.key.height = unit(0.5, "cm"),
  legend.key.width  = unit(0.5, "cm"),
  legend.direction = "horizontal",
  axis.title = element_text(size = 10),
  axis.text = element_text(size = 10),
  legend.margin = margin(t = -0.5, unit='cm'),
  legend.text = element_text(size =7),
  legend.title.position = "top",
  legend.title = element_text(size=7),
  legend.position = c(0.05, -0.12),
  
)
dev.off()
```

